version: "3.8"

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
