spring:
  datasource:
    url: jdbc:mysql://localhost:13306/test
    username: test
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    baselineOnMigrate: true
  profiles:
    active: local